### ISSUE TITLE
Dataset link cannot open

### ISSUE THREAD

**Issue by Coolspringbud** [shub-garg/Yoga-Pose-Classification-and-Skeletonization#1]
Hi, I can't open the Dataset link: https://drive.google.com/file/d/1yjzXqma96Xq-tX3dI8AvmjTDSqB2UR-i/view?usp=sharing.

**Comment by shub-garg** [comment]
Fixed. 
New link: https://www.kaggle.com/datasets/niharika41298/yoga-poses-dataset
